eureka:
  instance:
    preferIpAddress:
      true
  client:
    serviceUrl:
      defaultZone:
        http://10.210.81.38:8761/eureka/,http://10.210.81.40:8761/eureka/

service:
  register-url:
    http://10.210.81.38:8761/,http://10.210.81.40:8761/

spring:
  rabbitmq:
    host:
      10.210.81.40
    port:
      5672
    username:
      Admin
    password:
      Admin
    virtual-host:
      /
    publisher-confirms:
      true

foo:
  foo version tylxrex
